name: Archicad Add-On Windows Build

on:
  push:
    branches: [ archicad-addon ]

jobs:
  build_ac26:
    runs-on: [ windows-2019 ]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Download Development Kit
      run: python archicad-addon/Tools/download_and_unzip.py ${{ secrets.WIN_DEVKIT_AC26 }} archicad-addon/Tools/Build
    - name: Generate Project
      run: cmake -B archicad-addon/Tools/Build/AC26 -G "Visual Studio 16 2019" -A "x64" -T "v142" -DAC_API_DEVKIT_DIR="archicad-addon/Build/AC26/API Development Kit 26.3000" ..
    - name: Build Debug
      run: cmake --build archicad-addon/Build/AC26 --config Debug
    - name: Build RelWithDebInfo
      run: cmake --build archicad-addon/Build/AC26 --config RelWithDebInfo
