name: Archicad Add-On Mac Build

on:
  push:
    branches:
      - main
    paths:
      - 'archicad-addon/**'
      - '.github/workflows/**'
        
jobs:
  build_mac_ac25:
    runs-on: [ macos-12 ]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Download Development Kit
      run: python3 archicad-addon/Tools/download_and_unzip.py ${{ secrets.MAC_DEVKIT_AC25 }} archicad-addon/Build
    - name: Generate Project
      run: cmake -B archicad-addon/Build/AC25 -G "Xcode" -DCMAKE_OSX_ARCHITECTURES="x86_64" -DAC_API_DEVKIT_DIR="archicad-addon/Build/GRAPHISOFT ARCHICAD API DevKit 25.3006" archicad-addon
    - name: Build Debug
      run: cmake --build archicad-addon/Build/AC25 --config Debug
    - name: Build RelWithDebInfo
      run: cmake --build archicad-addon/Build/AC25 --config RelWithDebInfo

  build_mac_ac26:
    runs-on: [ macos-12 ]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Download Development Kit
      run: python3 archicad-addon/Tools/download_and_unzip.py ${{ secrets.MAC_DEVKIT_AC26 }} archicad-addon/Build
    - name: Generate Project
      run: cmake -B archicad-addon/Build/AC26 -G "Xcode" -DCMAKE_OSX_ARCHITECTURES="x86_64" -DAC_API_DEVKIT_DIR="archicad-addon/Build/Graphisoft Archicad API DevKit 26.3000" archicad-addon
    - name: Build Debug
      run: cmake --build archicad-addon/Build/AC26 --config Debug
    - name: Build RelWithDebInfo
      run: cmake --build archicad-addon/Build/AC26 --config RelWithDebInfo
